POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphIiwiaWQiOiI2NjJiNmMwOTcwZjU0YjFiYWIxZTIzN2MiLCJpYXQiOjE3MTQxMzIyNzN9.Z3A2JeH0xcXa8-1WDnf8fsq7Qc3vHP8_bvfCP0Enh3Y

{
    "title": "Hidjfkdfjdkfkdfjdehhhh blog",
    "author": "Me",
    "url": "www.ksdjkjdkjs",
    "likes": 30,
    "user": "662b6c0970f54b1bab1e237c"
}