DELETE http://localhost:3003/api/blogs/662b7e22e5facb1adffed347
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RhYWphIiwiaWQiOiI2NjJiNmMwOTcwZjU0YjFiYWIxZTIzN2MiLCJpYXQiOjE3MTQxMjY0Njd9.kADIkZFT0-izzecH0AUTB02lem1QGyxfwddkEZWDDY

