PUT http://localhost:3003/api/blogs/662285c27e9432e7269c4059
Content-Type: application/json

{
  "title": "Title",
  "author": "Author 2",
  "url": "moi",
  "likes": 20000,
  "id": "6623b8848f5915633f65d62e"
}
